application:
  name: chess-dev
  version: 0.0.1-ALPHA

spring:
  config:
    activate:
      on-profile: dev
  security:
    user:
      name: chess_service
      password: chess_service
    http:
      session-management:
        concurrency-control:
          max-sessions: 5